print('What is Your Name?')
name = input()
print('facinating.',name,'is my name too.')
print('Have you thought about blank hole today?')
yes_no = input()
print('I am so glad you said',yes_no,'.I was thinking the same thing')
